FROM node:lts-bullseye

# ARG USERNAME=node
# ARG USER_UID=2000
# ARG USER_GID=2001
# ARG GRPNAME=node

ENV DEBIAN_FRONTEND=noninteractive

# RUN addgroup -g $USER_GID $GRPNAME \
#     && adduser -u $USER_UID -g $GRPNAME -D $USERNAME
# RUN addgroup --gid $USER_GID $GRPNAME \
#     && adduser --uid $USER_UID $USERNAME \
#     && adduser $USERNAME $GRPNAME

# USER $USERNAME
